import type { AgentConfig, AgentResult, Finding } from "@xyavoryx/core";
import type { XyaVoryx } from "./xyavoryx";

export interface MultiAgentOrchestrationResult {
  sessionId: string;
  status: "completed" | "failed" | "blocked";
  findings: Finding[];
  reports: { agentName: string; report: string }[];
  consolidatedReport: string;
}

export class MultiAgentOrchestrator {
  constructor(private readonly runtime: XyaVoryx) {}

  async runPipeline(
    agents: AgentConfig[],
    startingTask: string,
    initialContext?: Record<string, unknown>
  ): Promise<MultiAgentOrchestrationResult> {
    const sessionId = (initialContext?.sessionId as string) ?? "orchestration-session-" + Math.floor(Math.random() * 1000000);
    const findings: Finding[] = [];
    const reports: { agentName: string; report: string }[] = [];
    
    let status: MultiAgentOrchestrationResult["status"] = "completed";
    let accumulatedObservations: string[] = [];
    let accumulatedFindingsSummary: string[] = [];

    // Initialize first context
    let currentContext: Record<string, unknown> = {
      ...initialContext,
      sessionId,
      previousObservations: [],
      previousFindings: []
    };

    for (let idx = 0; idx < agents.length; idx++) {
      const agent = agents[idx];
      
      // Inject accumulated state to ensure downstream agents remember previous accomplishments
      currentContext.previousObservations = accumulatedObservations.slice(-20);
      currentContext.previousFindings = accumulatedFindingsSummary.slice(-10);

      // Run this agent pipeline step
      const result: AgentResult = await this.runtime.runAgent(agent, {
        task: startingTask,
        context: currentContext
      });

      reports.push({
        agentName: agent.name,
        report: result.report ?? ""
      });

      if (result.findings && result.findings.length > 0) {
        findings.push(...result.findings);
        for (const f of result.findings) {
          accumulatedFindingsSummary.push(`[${f.severity.toUpperCase()}] ${f.title}: ${f.description}`);
        }
      }

      if (result.status === "failed") {
        status = "failed";
      } else if (result.status === "blocked" && status !== "failed") {
        status = "blocked";
      }

      // Collect trace observations from memory or logs for the next agent
      if (result.trace?.events) {
        for (const ev of result.trace.events) {
          if (ev.type === "observation.created" && ev.payload?.message) {
            accumulatedObservations.push(String(ev.payload.message));
          }
        }
      }

      // Chain session info
      currentContext = {
        ...currentContext,
        sessionId: result.sessionId
      };
    }

    // Build consolidated consolidated master report
    let consolidatedReport = `# Consolidated Executive Security Report\n\n`;
    consolidatedReport += `## Session Details\n`;
    consolidatedReport += `- **Session ID:** \`${sessionId}\`\n`;
    consolidatedReport += `- **Orchestrated Workflow Status:** **${status.toUpperCase()}**\n`;
    consolidatedReport += `- **Total Agents Involved:** ${agents.length}\n`;
    consolidatedReport += `- **Total Security Findings Discovered:** ${findings.length}\n\n`;

    consolidatedReport += `## Workflow Execution Timeline & Agent Outputs\n\n`;
    for (let idx = 0; idx < reports.length; idx++) {
      const r = reports[idx];
      consolidatedReport += `### Agent ${idx + 1}: ${r.agentName}\n`;
      consolidatedReport += `${r.report || "_No report generated by this agent._"}\n\n`;
      consolidatedReport += `---\n\n`;
    }

    consolidatedReport += `## Aggregated Security Findings Summary\n\n`;
    if (findings.length === 0) {
      consolidatedReport += `_No vulnerabilities or security findings were discovered during this orchestration pipeline._\n`;
    } else {
      consolidatedReport += `| Severity | Finding Title | Source Tool | CWE / OWASP |\n`;
      consolidatedReport += `| :--- | :--- | :--- | :--- |\n`;
      for (const f of findings) {
        const cweOwasp = [f.cwe, f.owasp].filter(Boolean).join(" / ");
        consolidatedReport += `| **${f.severity.toUpperCase()}** | ${f.title} | \`${f.sourceTool ?? "unknown"}\` | ${cweOwasp} |\n`;
      }
      consolidatedReport += `\n`;
    }

    return {
      sessionId,
      status,
      findings,
      reports,
      consolidatedReport
    };
  }
}
